#!/bin/bash

# list-tags-hashes
# Allan Peda <allan.peda@gmail.com>
# Example usage:
# (base) -bash-4.4$ list-tag-hashes | grep -F '2.4.62'
# f4c1e18 2024-07-17 2.4.62
# 2184997 2024-07-15 2.4.62-rc1-candidate

set -eEuo pipefail

declare FORMAT='S'
if [[ "$#" -gt 0 && "${#1}" -gt 0 ]]
then
    if [[ "$1" == '--long' ]]
    then
        FORMAT='L'
    fi
fi

declare -ri HASHLEN=40
declare -r  REFSTAGS=' refs/tags/'
declare objtype objhash commit_hash datestring
while read -r reftag
do
   objhash="${reftag:0:${HASHLEN}}"
   objtype="$(git cat-file -t "${objhash}")"
   if [[ "$objtype" == 'tag' ]]
   then
       commit_hash="$(git rev-parse "${objhash}"^{})"
       if [[ "$FORMAT" == 'L' ]]
       then
           datestring="$(git show -s --format=%cd --date=format:'%Y-%m-%d %H:%M:%S %z' "$commit_hash")"
           echo "${commit_hash} ${datestring} ${reftag:(${HASHLEN}+1)}"
       else
           datestring="$(git show -s --format=%cd --date=short "$commit_hash")"
           echo "${commit_hash:0:7} ${datestring} ${reftag#*"${REFSTAGS}"}"
       fi

   fi
done < <(git show-ref --tags)
